### ISSUE TITLE
Windows 8.1 no reconoce la tarjeta Bast-Pro-Mini-M0

### ISSUE THREAD

**Issue by AAngelBauNino** [ElectronicCats/Bast-Pro-Mini-M0#3]
Hola que tal tengo el siguiente conflicto: Al conectar la tarjeta Bast-Pro-Mini-M0 por cualquiera de los puertos USB este lo detecta pero aparece en la seccion de otros dispositivos con un triangulo amarillo y un signo de admiracion, obviamente esto significa que el driver no se instalo, me pueden apoyar para darle solucion a este problema. 
Sera que habra que modificar el driver instalado en el ATSAMD21E18 o reconfigurarlo?
Este cambio se puede hacer desde el mismo puerto USB o se tiene que usar el puerto JTAG?

Bueno abro el hilo para dar solucion a esto.
Saludos!
![128017127_827439054718103_1858007930482252882_n](https://user-images.githubusercontent.com/75118518/100804062-cfb7db80-33f1-11eb-9620-910f355c60bb.jpg)

**Comment by sabas1080** [comment]
Hola @AngelBNShark 

Windows 8.1 parece tener bastantes problemas con drivers en general, parece puede ser la firma de drivers segun este hilo, por favor probar y me cuentas https://forum.arduino.cc/index.php?topic=445796.0

**Comment by AAngelBauNino** [comment]
Gracias por tu respuesta, leó, implemento y comento ;)

**Comment by AAngelBauNino** [comment]
Hola @sabas1080 

segui el procedimiento del link que me compartiste: desactive la firma de controladores de windows, re-instale el paquete de Arduino SAM Boards, conecte la bast pro mini y naranjas, sigue igual :(

**Comment by sabas1080** [comment]
@AngelBNShark debes reinstalar arduino IDE y los drivers

**Comment by sabas1080** [comment]
@AngelBNShark puedes probar usando https://zadig.akeo.ie/ ? Si no tendras que esperar a que generemos los drivers para Windows 8.1 y versiones pasadas

**Comment by AAngelBauNino** [comment]
Hola, hoy la conecte a una pc con Windows 7 y tampoco lo instaló.

Unas preguntas:
En que sistemas operativos la han probado?
A tu experiencia con este micro que programador recomiendas o debugger recomiendas para estos micros?

Un gran saludo!!! ![error Bast.png](https://user-images.githubusercontent.com/75118518/100910514-b8312f00-3493-11eb-8da2-e051681c34e5.png)

**Comment by AAngelBauNino** [comment]
En Windows 8.1 reinstalé el IDE y el paquete de tarjetas, tampoco dio solución :(

**Comment by sabas1080** [comment]
@AngelBNShark 
- Linux, Mac y Windows 10 esta probado
- Jlink o Blackmagic para depuracion, tambien hemos usado nuestro DAPCat
- Trata con https://zadig.akeo.ie/ en Windows 7 y Windows 8.1

**Comment by AAngelBauNino** [comment]
Hola, trate instalando un drive con "Zadig" y exito! este instala un controlador, pero el ID de Arduino no lo reconoce :'(.
Sigo investigando una solución ;)

Saludos.

**Comment by AAngelBauNino** [comment]
Hola que tal, ya quedo :D, la solución fue instalar un controlador usando "Zadig" con la opción  "USB Serial (CDC)", no había visto esta opción, funciona bien tanto en windows 7 y como en windows 8.1. Gracias!

Un gran saludo.

**Comment by sabas1080** [comment]
Excelente, gracias @AngelBNShark , voy agregar las instrucciones al README para Windows 7 y Windows 8.1
