### ISSUE TITLE
PWM 

### ISSUE THREAD

**Issue by NeftaliVenancio** [ElectronicCats/Bast-Pro-Mini-M0#6]
¿Podrían indicarme cuales son los pines habilitados para PWM?

**Comment by Marcelol52** [comment]
Hola Neftali,

Los pines que están habilitados para PWM en la variante de nuestro core son: 9 y 10.  Y aparte se pueden activar: 5 y 6 desde la variante de nuestro core.

Espero te sea de utilidad.

**Comment by NeftaliVenancio** [comment]
Podras compartirme la documentación para habilitar 5 y 6 por favor.

**Comment by Marcelol52** [comment]
Hola Neftali,

Si estas usando el IDE de Arduino en Windows, puedes encontrar la variante en la ruta: \AppData\Local\Arduino15\packages\electroniccats\hardware\samd\2.1.2\variants\bast_pro_mini_m0\variant.cpp

Para otros sistemas operativos la ruta es similar.

**Comment by Marcelol52** [comment]
Hola Neftali,

Si estas usando el IDE de Arduino en Windows, puedes encontrar la variante en la ruta: \AppData\Local\Arduino15\packages\electroniccats\hardware\samd\2.1.2\variants\bast_pro_mini_m0\variant.cpp

Para otros sistemas operativos la ruta es similar.

Actualmente no tenemos documentación acerca de esto para la tarjeta, estamos trabajando en ellos. Pero puedes referirte al manual de usuario u hoja de datos del microcontrolador y encontrar la información pertinente ahí.

**Comment by Marcelol52** [comment]
<html>
Hola Neftali,

Después de revisar más la variante encontré que estos pines son los que pueden generar PWM, en la tabla también te comparto el reloj que usa cada uno. Adjunté también dos imágenes que muestran como hay que modificar la variante para que  se pueda generar el PWM. El proceso es sencillo, es cambiar ya sea el reloj existente o la etiqueta de 'NOT_ON_TIMER' por el reloj que viene en la tabla. Hice algunas pruebas con nuestro osciloscopio y la señal se genera bien.  Espero esto te sea de más ayuda, Cualquier problema no dudes en contactarnos de nuevo. 



<body>
<google-sheets-html-origin><style type="text/css"></style>

Port | PIN | MCU | TC/TCC
-- | -- | -- | --
A | 3 | PA23 | TC4_CH1
A | 4 | PA22 | TC4_CH0
A | 5 | PA15 | TC3_CH1
A | 8 | PA06 | TCC1_CH0
A | 9 | PA07 | TCC1_CH1
A | 10 | PA18 | TC3_CH0
A | 12 | PA19 | TC3_CH1
A | 13 | PA17 | TCC2_CH1


</body>
</html>

![image](https://github.com/ElectronicCats/Bast-Pro-Mini-M0/assets/139595394/6593018b-8dcd-4904-aa32-600d328e7277)

![image](https://github.com/ElectronicCats/Bast-Pro-Mini-M0/assets/139595394/37d38b8c-65ad-40a3-96d6-5a72be6598b4)

**Comment by NeftaliVenancio** [comment]
Gracias

**Comment by NeftaliVenancio** [comment]
Tendras algun codigo de ejemplo para usar los pines 9 y 10, el unico que me esta respondiendo corectamente es el A0 usando el DAC

**Comment by Marcelol52** [comment]
Te comparto abajo el código que utilicé para probar el PWM en los pines 9 y 10. Solo recurda que se tiene que hacer un cambio el la variante de la tarjeta para activar el PWM. Solo se tiene que cambiar el reloj que se está usando para ese PIN. Si estas usando el IDE de Arduino, puedes encontrar la variante para modificarla en la ruta: \AppData\Local\Arduino15\packages\electroniccats\hardware\samd\2.1.2\variants\bast_pro_mini_m0\variant.cpp

Original
```
 // 9 - PA07 -  GPIO - PWM
  { PORTA,  7, PIO_MULTI, (PER_ATTR_DRIVE_STD|PER_ATTR_TIMER_STD), (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER), TCC1_CH0, No_ADC_Channel, EXTERNAL_INT_7, GCLK_CCL_NONE }, // TCC0/WO[1]

  // SPI SERCOM3
  // 10 - PA18 -  GPIO - PWM - SS(SPI) 
  { PORTA,  18, PIO_SERCOM, (PER_ATTR_DRIVE_STD|PER_ATTR_TIMER_STD), (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PER_ATTR_SERCOM_ALT), TCC0_CH0, No_ADC_Channel, EXTERNAL_INT_2, GCLK_CCL_NONE },  // TCC0/WO[0]
```
Cambio para hacer funcionar el PWM
```
  // 9 - PA07 -  GPIO - PWM
  { PORTA,  7, PIO_MULTI, (PER_ATTR_DRIVE_STD|PER_ATTR_TIMER_STD), (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER), TCC1_CH1, No_ADC_Channel, EXTERNAL_INT_7, GCLK_CCL_NONE }, // TCC0/WO[1]

  // SPI SERCOM3
  // 10 - PA18 -  GPIO - PWM - SS(SPI) 
  { PORTA,  18, PIO_SERCOM, (PER_ATTR_DRIVE_STD|PER_ATTR_TIMER_STD), (PIN_ATTR_DIGITAL|PIN_ATTR_TIMER|PER_ATTR_SERCOM_ALT), TC3_CH0, No_ADC_Channel, EXTERNAL_INT_2, GCLK_CCL_NONE },  // TCC0/WO[0]
```
Código
```

//const int led_pwm = 9 ;	// Definimos la salida PWM 
const int led_pwm = 10 ;	// Definimos la salida PWM 
int adc_nuevo = 0 ;   	// Usamos entrada ADC en pin A0
int adc_viejo = 0 ;   	// Guardamos la última lectura del ADC

void setup() {
  // Inicializamos el puerto serie
  Serial.begin(9600);

  // Configuramos pwm como salida
  pinMode(led_pwm, OUTPUT) ;     
}

void loop() {
  // Leemos el valor del ADC en el pin A0  usando un POT de 10k
  adc_nuevo  = analogRead(A0) ;  

  // Ajustamos el valor leido en A0 para adaptarlo al rengo
  // del PWM. Se adapta la escala de 0-1023 a 0-255  
  adc_nuevo = map(adc_nuevo, 0, 1023, 0, 255);  

  if (adc_nuevo != adc_viejo) {
    // Actualiza la lectura del ADC
    adc_viejo = adc_nuevo;

    // Envia el valor actual al puerto serie
    Serial.println(adc_nuevo);

    // Envia el valor adaptado al PWM
    analogWrite(led_pwm, adc_nuevo); 
  }
}
```

Espero esta información te sea de ayuda, si tienes más dudas no dudes en contactarnos de nuevo.

**Comment by NeftaliVenancio** [comment]
ok, por defecto como viene el core a la hora instalara la tarjeta ¿No se puede usar ningún pin como PWM sin necesidad de hacer la modificación?

**Comment by Marcelol52** [comment]
Lo pines que pueden generar PWM con el core como está son: pines digitales, 1 y 13. En cuanto a los pines análogos, estos no generan como tal un PWM, pueden regular la salida de voltage pero no es a traves de una regulación del ancho del pulso.

**Comment by NeftaliVenancio** [comment]
¿todos los analógicos pueden regular el voltaje o solo el A0 a través del DAC?

**Comment by Marcelol52** [comment]
El A0 es el unico que tiene un DAC para hacer esa regulación de voltage. Y realizando más se puede hacer PWM con A1 también con el core como está. En total serian pines digitals D1,D13,A1 y el A0 con DAC.
